### ISSUE TITLE
[Feature] Cancel auto stop

### ISSUE THREAD

**Issue by jafdy** [Zingabopp/OBSControl#17]
When I record map testplays the map will sometimes break and need to be restarted, I prefer to do this into a single take (doesn't need to re-render or for the mapper to look at multiple vids) so I need to prevent it from auto stopping. Currently I do this by disconnecting from the in-game menu but it doesn't reconnect without a full game restart. 
I would like to have a button to force it to not stop until I manually stop it for this recording only.

**Comment by Zingabopp** [comment]
v2.x.x beta has an in-game UI with the `Enable AutoRecord` option. Disabling this will also disable auto-stop as long as you start the recording manually.
