### ISSUE TITLE
Autorecord keeps enabling itself

### ISSUE THREAD

**Issue by Arimodu** [Zingabopp/OBSControl#28]
I don't want to use automatic recording at all, I want just a panel for controlling OBS when streaming & recording. Every time I either reload settings or restart the game the panel unlocks itself and Autorecord enables itself, also overwrites the json settings.

**Comment by Arimodu** [comment]
Correction, no settings are saved after reload/restart

**Comment by Zingabopp** [comment]
The Enable AutoRecord in the panel is just for the session, if you want to make it permanent you should be able to disable it in the Mod Settings menu.

**Comment by Zingabopp** [comment]
It's also possible I forgot to include that in the settings menu...

**Comment by Arimodu** [comment]
Well there is the auto stop but I cant find the autostart toggle

**Comment by Zingabopp** [comment]
Should be fixed in the latest `dev` build. The game panel toggle is now saved between game sessions. https://github.com/Zingabopp/OBSControl/runs/2232057744?check_suite_focus=true
