### ISSUE TITLE
OBS 28 compatibility

### ISSUE THREAD

**Issue by brian-gates** [Zingabopp/OBSControl#41]
OBS released version 28, which appears to break compatibility.

```
[WARNING @ 15:07:03 | OBSControl] Failed to connect to server ws://127.0.0.1:4445, OBSWebsocket not running?
[WARNING @ 15:07:10 | OBSControl] Failed to connect to server ws://127.0.0.1:4445, OBSWebsocket not running?
[WARNING @ 15:07:17 | OBSControl] Failed to connect to server ws://127.0.0.1:4445, OBSWebsocket not running?
[WARNING @ 15:07:24 | OBSControl] Failed to connect to server ws://127.0.0.1:4445, OBSWebsocket not running?
[WARNING @ 15:07:31 | OBSControl] Failed to connect to server ws://127.0.0.1:4445, OBSWebsocket not running?
[WARNING @ 15:07:31 | OBSControl] OBS is not connected, automatic connect aborted after 5 attempts.
```

Per [obs-websocket's README](https://github.com/obsproject/obs-websocket#downloads), 

> obs-websocket is now included by default with OBS Studio 28.0.0 and above. As such, there should be no need to download obs-websocket if you have OBS Studio > 28.0.0.

**Comment by brian-gates** [comment]
I was able to get it working with https://github.com/obsproject/obs-websocket/releases/tag/4.9.1-compat!

> Install this version only if you require legacy 4.9.1 protocol support and are using OBS 28.0.0 or above

**Comment by Gordin** [comment]
Hm, I think this should be reopened because OBS 28 is the default now and the instructions in the README are just wrong now. There should at least be a mention of the obs-websocket compat plugin in the README, or an open issue about this ^^
