### ISSUE TITLE
Not recording My extremely good scores

### ISSUE THREAD

**Issue by Coolsplo1t** [Zingabopp/OBSControl#9]
So Ive used obscontrol while recording 3 top 10 leaderboard scores on official beat saber songs and uh I dont know if its in a seprate folder but none of them recorded, others worked perfectly

**Comment by Zingabopp** [comment]
If you can find it, please post the `Beat Saber\Logs\_latest.log` from the session where the recordings failed to start.  The names of the songs that weren't recorded would be helpful too. Also, did the successful recordings occur during the same game session (Beat Saber wasn't restarted)?

Without more info, the only things I can think of that would cause a recording not to start are:
* No disk space
* The next level was started before the last recording was finished (although I'm pretty sure it will immediately end the previous recording and start the next one)

**Comment by PaperT1D** [comment]
> although I'm pretty sure it will immediately end the previous recording and start the next one

Not OP but wanted to comment on this.

I would say this is usually or often the case, and the files that get created in those instances don't get renamed and keep their default name structure (such as date/time). That's not a huge deal most of the time, though I have had file renaming go wrong (in that it assigned the file name to the wrong file). It becomes more of a problem when a new recording "doesn't start" and, with no current in-game indicator of recording status, it's easy to miss when that happens until it's too late. The times a recording doesn't start, sometimes it resolves itself and on the next song you start, recording will resume as normal. Other times it does literally nothing and it is as if the mod is disabled. I generally just restart both OBS and Beat Saber when this happens and things work fine again.

Basically it boils down to one unfortunate thing: you have to slow down between songs if you are using this mod, especially if you use start or stop delays. That also means not using the replay button unless you're willing to take the chances. It's not much time to wait between songs to make sure your recording has finished and OBS is ready for the next one, but it can feel like a lot when you just want to play without some other background worry about the game or what your mods are doing or not doing. Sometimes I get into a state where I play song after song, or am doing something on repeat (I'll attach a log from today showing this happening), and if there isn't enough time between a recording stopping and a new one starting, it's pretty likely that you are going to have files that have not been renamed by the mod, and/or you will have missing recordings completely.

It's annoying to have to be careful or think about it, but I have been using this mod for about a month and a half, and even with the hiccups and improvements that could be made, I'd rather not go without it. I went from recording full play sessions (sometimes several hours long), to manually recording/stopping/repeat any time I wanted to save something specific, to saving OBS replays on demand in 7 minute chunks, to this. This is easily the winner imo, you just have to be a little patient with it and learn how to work around the weird stuff that can happen. If you don't give OBS the time, it won't be able to do its job for you.

[Here is a section of the log](https://github.com/Zingabopp/OBSControl/files/4942855/OBSControl_20200718_recording-already-active.txt). I cut it off there when things were working consistently. This is all that is relevant I think, but I can attach the rest of it if for some reason you need it.

For reference, files renamed, not renamed, and missing (if you compare to the log).
![OBSControl_20200718_recording-already-active](https://user-images.githubusercontent.com/38975109/87863624-7bb8c880-c922-11ea-84eb-79b9285a70ce.png)

**Comment by Zingabopp** [comment]
In-game display is coming soon:tm:. It'll be a floating window you can drag around with stats (recording status, skipped frames, free disk space, etc) and a button to start/stop recording.

**Comment by Zingabopp** [comment]
Here's a build with the WIP floating status screen. You'll need the latest BeatSaberMarkupLanguage (v1.3.3) to use it. The `Enable AutoRecord` checkbox does not currently do anything.
https://github.com/Zingabopp/OBSControl/actions/runs/182823927

**Comment by Zingabopp** [comment]
Latest v1 should be more reliable, v2.x.x beta has an in-game UI to show if OBS is recording

**Comment by Gordin** [comment]
> 
> 
> Latest v1 should be more reliable, v2.x.x beta has an in-game UI to show if OBS is recording

@Zingabopp FWIW, for me personally v2 is much more reliable than v1. In the past I lost recordings regularly on v1, but since I've been using the v2 branch (since BeatSaber 0.13.X ?) I haven't lost a single one, even when doing stuff like restart repeatedly while recording.
